# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalogue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61talogue.proto\x12\x04grpc\"\"\n\x0cItemsRequest\x12\x12\n\nitemsLimit\x18\x01 \x01(\x05\"\x88\x01\n\x05Items\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.grpc.Items.Item\x1a^\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\x05image\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06rating\x18\x04 \x01(\x02H\x01\x88\x01\x01\x42\x08\n\x06_imageB\t\n\x07_rating\":\n\x12ItemDetailsRequest\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x14\n\x0creviewsLimit\x18\x02 \x01(\x05\"\xfe\x01\n\x0bItemDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\x05image\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06rating\x18\x04 \x01(\x02H\x01\x88\x01\x01\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12)\n\x07reviews\x18\x06 \x03(\x0b\x32\x18.grpc.ItemDetails.Review\x1aW\n\x06Review\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x12\x14\n\x07\x63omment\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_commentB\x08\n\x06_imageB\t\n\x07_rating2\x81\x01\n\tCatalogue\x12\x35\n\x12listCatalogueItems\x12\x12.grpc.ItemsRequest\x1a\x0b.grpc.Items\x12=\n\x0egetItemDetails\x12\x18.grpc.ItemDetailsRequest\x1a\x11.grpc.ItemDetailsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalogue_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMSREQUEST._serialized_start=25
  _ITEMSREQUEST._serialized_end=59
  _ITEMS._serialized_start=62
  _ITEMS._serialized_end=198
  _ITEMS_ITEM._serialized_start=104
  _ITEMS_ITEM._serialized_end=198
  _ITEMDETAILSREQUEST._serialized_start=200
  _ITEMDETAILSREQUEST._serialized_end=258
  _ITEMDETAILS._serialized_start=261
  _ITEMDETAILS._serialized_end=515
  _ITEMDETAILS_REVIEW._serialized_start=407
  _ITEMDETAILS_REVIEW._serialized_end=494
  _CATALOGUE._serialized_start=518
  _CATALOGUE._serialized_end=647
# @@protoc_insertion_point(module_scope)
