# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import catalogue_pb2 as catalogue__pb2


class CatalogueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.listCatalogueItems = channel.unary_unary(
                '/grpc.Catalogue/listCatalogueItems',
                request_serializer=catalogue__pb2.ItemsRequest.SerializeToString,
                response_deserializer=catalogue__pb2.Items.FromString,
                )
        self.getItemDetails = channel.unary_unary(
                '/grpc.Catalogue/getItemDetails',
                request_serializer=catalogue__pb2.ItemDetailsRequest.SerializeToString,
                response_deserializer=catalogue__pb2.ItemDetails.FromString,
                )


class CatalogueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def listCatalogueItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getItemDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'listCatalogueItems': grpc.unary_unary_rpc_method_handler(
                    servicer.listCatalogueItems,
                    request_deserializer=catalogue__pb2.ItemsRequest.FromString,
                    response_serializer=catalogue__pb2.Items.SerializeToString,
            ),
            'getItemDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.getItemDetails,
                    request_deserializer=catalogue__pb2.ItemDetailsRequest.FromString,
                    response_serializer=catalogue__pb2.ItemDetails.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Catalogue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Catalogue(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def listCatalogueItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Catalogue/listCatalogueItems',
            catalogue__pb2.ItemsRequest.SerializeToString,
            catalogue__pb2.Items.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getItemDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Catalogue/getItemDetails',
            catalogue__pb2.ItemDetailsRequest.SerializeToString,
            catalogue__pb2.ItemDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
